name: build with nix
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_and_test:
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'macos-14']
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v15
      with:
        name: tket
        signingKey: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Build and test pytket-qir
      run: nix flake check -L
