name: Type check pytket-qir

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  many:
    name: Type check pytket-qir
    strategy:
      matrix:
        python-version: ['3.10']
        os: ['ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip install mypy
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mypy~=0.960
      - name: Run mypy
        run: |
          mypy .
